version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.api
    ports:
      - "3001:3001"
    env_file:
      - api/.env
    volumes:
      - ./api/uploads:/app/uploads   # keep uploads in dev
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.web
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:3001   # adjust if you switch to VITE
    restart: unless-stopped