const { body, param } = require("express-validator");

/**
 * Validation rules for creating a new subscription.
 */
const createSubscriptionValidation = [
  // The priceId must be a non-empty string sent from the client
  body("priceId")
    .notEmpty()
    .withMessage("Price ID is required.")
    .isString()
    .withMessage("Price ID must be a string."),

  // The paymentMethodId generated by Stripe Elements on the frontend
  body("paymentMethodId")
    .notEmpty()
    .withMessage("Payment Method ID is required.")
    .isString()
    .withMessage("Payment Method ID must be a string."),
];

// For attaching a new payment method or setting the default
const paymentMethodIdBodyValidation = [
  body("paymentMethodId")
    .notEmpty()
    .withMessage("Payment Method ID is required.")
    .isString(),
];

// For detaching a payment method from the URL
const paymentMethodIdParamValidation = [
  param("paymentMethodId")
    .notEmpty()
    .withMessage("Payment Method ID is required in the URL.")
    .isString(),
];

module.exports = {
  createSubscriptionValidation,
  paymentMethodIdBodyValidation, 
  paymentMethodIdParamValidation,
};
